---
- name: Setup KVM
  hosts: "{{ target_hosts | default('kvm_hosts') }}"
  become: true
  tasks:
    - name: Include install tasks
      ansible.builtin.include_role:
        name: kvm
        tasks_from: install.yml
